// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type DataBaseDocument struct {
	ID        string     `json:"id"`
	VersionID string     `json:"versionID"`
	Content   string     `json:"content"`
	Database  *Database  `json:"database"`
	CreateAt  *time.Time `json:"createAt"`
}

type Database struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Host     string     `json:"host"`
	Port     int        `json:"port"`
	Username string     `json:"username"`
	Password string     `json:"password"`
	Schema   string     `json:"schema"`
	Comment  string     `json:"comment"`
	CreateAt *time.Time `json:"createAt"`
	UpdateAt *time.Time `json:"updateAt"`
	Genre    *Genre     `json:"genre"`
	User     *User      `json:"user"`
}

type Genre struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	CreateAt *time.Time `json:"create_at"`
	UpdateAt *time.Time `json:"update_at"`
}

type GenreInput struct {
	ID string `json:"id"`
}

type NewDatabaseInput struct {
	Name     string      `json:"name"`
	Host     string      `json:"host"`
	Port     int         `json:"port"`
	Username string      `json:"username"`
	Password string      `json:"password"`
	Schema   string      `json:"schema"`
	Comment  string      `json:"comment"`
	Genre    *GenreInput `json:"genre"`
	User     *UserInput  `json:"user"`
}

type NewUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Page struct {
	Page     *int `json:"page"`
	PageSize *int `json:"pageSize"`
}

type UpdataUserInput struct {
	Name     string `json:"name"`
	Email    string `json:"email"`
	Password string `json:"password"`
}

type User struct {
	ID       string     `json:"id"`
	Name     string     `json:"name"`
	Email    string     `json:"email"`
	Password string     `json:"password"`
	CreateAt *time.Time `json:"createAt"`
	UpdateAt *time.Time `json:"updateAt"`
}

type UserInput struct {
	ID string `json:"id"`
}

type UpdateDatabaseInput struct {
	ID       string      `json:"id"`
	Name     string      `json:"name"`
	Host     string      `json:"host"`
	Port     int         `json:"port"`
	Username string      `json:"username"`
	Password string      `json:"password"`
	Schema   string      `json:"schema"`
	Comment  string      `json:"comment"`
	Genre    *GenreInput `json:"genre"`
}
