datasource:
  driver: mysql
  url: "@tcp(47.94.221.199)/dbdms?charset=utf8mb4&parseTime=True&loc=Local"
  username: yhkl 
  password: 123456
  max-open-conns: 100
  max-idle-conns: 10
  show-sql: true
  singular-table: true

